import { Imovies } from "../model/movie";


export const moviesArry : Array<Imovies> = [
    {
        adult: false,
        backdrop_path: "/path1.jpg",
        genre_ids: [28],
        id: 101,
        original_language: "en",
        original_title: "The Dark Knight",
        overview: "Batman raises the stakes in his war on crime...",
        popularity: 950.45,
        poster_path: "https://static1.colliderimages.com/wordpress/wp-content/uploads/2023/06/wp10441077-cropped.jpg",
        release_date: "2008-07-18",
        title: "The Dark Knight",
        video: false,
        vote_average: 9.0,
        vote_count: 28000
    },
    {
        adult: false,
        backdrop_path: "/path2.jpg",
        genre_ids: [12, 28],
        id: 102,
        original_language: "en",
        original_title: "Avengers: Endgame",
        overview: "The Avengers assemble once more in order to undo Thanos' actions...",
        popularity: 1200.22,
        poster_path: "https://images.wallpapersden.com/image/download/poster-of-avengers-endgame-movie_a2htaGWUmZqaraWkpJRmbmdlrWZlbWU.jpg",
        release_date: "2019-04-26",
        title: "Avengers: Endgame",
        video: false,
        vote_average: 8.5,
        vote_count: 35000
    },
    {
        adult: false,
        backdrop_path: "/path3.jpg",
        genre_ids: [878, 28],
        id: 103,
        original_language: "en",
        original_title: "Inception",
        overview: "A thief who enters the dreams of others to steal secrets...",
        popularity: 800.11,
        poster_path: "https://wallpaperaccess.com/full/1264684.jpg",
        release_date: "2010-07-16",
        title: "Inception",
        video: false,
        vote_average: 8.8,
        vote_count: 29000
    },
    {
        adult: false,
        backdrop_path: "/path4.jpg",
        genre_ids: [12, 28],
        id: 104,
        original_language: "en",
        original_title: "Spider-Man: No Way Home",
        overview: "Peter Parker seeks Doctor Strange's help to restore his secret identity...",
        popularity: 1100.55,
        poster_path: "https://wallpaperaccess.com/full/7792173.jpg",
        release_date: "2021-12-17",
        title: "Spider-Man: No Way Home",
        video: false,
        vote_average: 8.3,
        vote_count: 20000
    },
    {
        adult: false,
        backdrop_path: "/path5.jpg",
        genre_ids: [28, 53],
        id: 105,
        original_language: "en",
        original_title: "John Wick",
        overview: "An ex-hitman comes out of retirement to track down gangsters...",
        popularity: 780.33,
        poster_path: "https://i.pinimg.com/originals/44/c4/4c/44c44c3a514a0f20f5e58a7f6d3f772d.jpg",
        release_date: "2014-10-24",
        title: "John Wick",
        video: false,
        vote_average: 7.5,
        vote_count: 15000
    },
    {
        adult: false,
        backdrop_path: "/path6.jpg",
        genre_ids: [28, 12],
        id: 106,
        original_language: "en",
        original_title: "Gladiator",
        overview: "A former Roman General sets out to exact vengeance...",
        popularity: 720.12,
        poster_path: "https://img.freepik.com/premium-photo/gladiator-stands-stadium-with-large-crowd-him_256339-4105.jpg?w=1060",
        release_date: "2000-05-05",
        title: "Gladiator",
        video: false,
        vote_average: 5.5,
        vote_count: 18000
    },
    {
        adult: false,
        backdrop_path: "/path7.jpg",
        genre_ids: [28, 12],
        id: 107,
        original_language: "en",
        original_title: "Black Panther",
        overview: "T'Challa returns home as king of Wakanda but finds his sovereignty challenged...",
        popularity: 840.77,
        poster_path: "https://wallpaperbat.com/img/82221140-black-panther-art-wallpaper-4k-hd-pc-i.jpg",
        release_date: "2018-02-16",
        title: "Black Panther",
        video: false,
        vote_average: 7.3,
        vote_count: 19000
    },
    {
        adult: false,
        backdrop_path: "/path8.jpg",
        genre_ids: [16, 12, 10751],
        id: 108,
        original_language: "en",
        original_title: "Toy Story",
        overview: "A cowboy doll is profoundly threatened and jealous...",
        popularity: 690.21,
        poster_path: "https://cdn.kinocheck.com/i/fviyg44xlx.jpg",
        release_date: "1995-11-22",
        title: "Toy Story",
        video: false,
        vote_average: 8.2,
        vote_count: 14000
    },
    {
        adult: false,
        backdrop_path: "/path9.jpg",
        genre_ids: [878, 28],
        id: 109,
        original_language: "en",
        original_title: "The Matrix",
        overview: "A computer hacker learns about the true nature of his reality...",
        popularity: 970.45,
        poster_path: "https://static1.srcdn.com/wordpress/wp-content/uploads/2025/02/the-matrix-casting-will-smith-as-neo-over-keanu-reeves-would-have-led-to-another-massive-change-from-what-we-got.jpg",
        release_date: "1999-03-31",
        title: "The Matrix",
        video: false,
        vote_average: 8.7,
        vote_count: 21000
    },
    {
        adult: false,
        backdrop_path: "/path10.jpg",
        genre_ids: [28, 53],
        id: 110,
        original_language: "en",
        original_title: "Mad Max: Fury Road",
        overview: "In a post-apocalyptic wasteland, Max teams up with Furiosa...",
        popularity: 820.12,
        poster_path: "https://images.wallpapersden.com/image/download/mad-max-fury-road-vehicles-wallpapers_aWVmZmyUmZqaraWkpJRpbmdtrWhnbWU.jpg",
        release_date: "2015-05-15",
        title: "Mad Max: Fury Road",
        video: false,
        vote_average: 8.1,
        vote_count: 16000
    },
    {
        adult: false,
        backdrop_path: "/path3.jpg",
        genre_ids: [12, 14],
        id: 103,
        original_language: "en",
        original_title: "The Lord of the Rings: The Return of the King",
        overview: "Gandalf and Aragorn lead the World of Men against Sauron's army...",
        popularity: 790.11,
        poster_path: "https://m.media-amazon.com/images/I/51Qvs9i5a%2BL._AC_.jpg",
        release_date: "2003-12-17",
        title: "The Lord of the Rings: The Return of the King",
        video: false,
        vote_average: 9.1,
        vote_count: 25000
    },
    {
        adult: false,
        backdrop_path: "/path4.jpg",
        genre_ids: [878, 12],
        id: 104,
        original_language: "en",
        original_title: "Interstellar",
        overview: "A team of explorers travel through a wormhole in space...",
        popularity: 860.77,
        poster_path: "https://wallpapercrafter.com/desktop/66240-interstellar-movies.jpg",
        release_date: "2014-11-07",
        title: "Interstellar",
        video: false,
        vote_average: 8.7,
        vote_count: 22000
    },
    {
        adult: false,
        backdrop_path: "/path6.jpg",
        genre_ids: [28, 12, 878],
        id: 106,
        original_language: "en",
        original_title: "Avengers: Infinity War",
        overview: "The Avengers must stop Thanos from collecting the Infinity Stones...",
        popularity: 940.6,
        poster_path: "https://images.hdqwalls.com/wallpapers/avengers-infinity-war-2018-all-characters-poster-1s.jpg",
        release_date: "2018-04-27",
        title: "Avengers: Infinity War",
        video: false,
        vote_average: 8.4,
        vote_count: 23000
    },
    {
        adult: false,
        backdrop_path: "/path8.jpg",
        genre_ids: [16, 10751],
        id: 108,
        original_language: "en",
        original_title: "Finding Nemo",
        overview: "After his son is captured in the Great Barrier Reef...",
        popularity: 720.9,
        poster_path: "https://wallpapercrafter.com/desktop2/788398-Finding-Nemo-Bruce-Finding-Nemo-Dory-Finding-Nemo.jpg",
        release_date: "2003-05-30",
        title: "Finding Nemo",
        video: false,
        vote_average: 8.2,
        vote_count: 16000
    },
    {
        adult: false,
        backdrop_path: "/path9.jpg",
        genre_ids: [35, 18, 10749],
        id: 109,
        original_language: "en",
        original_title: "Forrest Gump",
        overview: "The presidencies of Kennedy and Johnson, Vietnam, and more...",
        popularity: 690.1,
        poster_path: "https://m.media-amazon.com/images/S/pv-target-images/5217d6fa076801fdbf3943960898e6665fcb2502ae06f7394b600b10d8894add._SX1080_FMjpg_.jpg",
        release_date: "1994-07-06",
        title: "Forrest Gump",
        video: false,
        vote_average: 8.9,
        vote_count: 19000
    },
    {
        adult: false,
        backdrop_path: "/path10.jpg",
        genre_ids: [28, 80, 53],
        id: 110,
        original_language: "en",
        original_title: "Joker",
        overview: "In Gotham City, mentally troubled comedian Arthur Fleck...",
        popularity: 810.4,
        poster_path: "https://wallpapercave.com/wp/wp10887007.jpg",
        release_date: "2019-10-04",
        title: "Joker",
        video: false,
        vote_average: 8.6,
        vote_count: 21000
    },
    {
        adult: false,
        backdrop_path: "/path13.jpg",
        genre_ids: [35, 18, 10749],
        id: 113,
        original_language: "en",
        original_title: "Titanic",
        overview: "A love story doomed by the sinking of the RMS Titanic...",
        popularity: 950.8,
        poster_path: "https://preview.redd.it/in-the-1997-film-titanic-directed-by-james-cameron-the-main-v0-aw0rl10k0uka1.png?auto=webp&s=8d62dabd4643529131bfcd62613c39e0e55c2fb7",
        release_date: "1997-12-19",
        title: "Titanic",
        video: false,
        vote_average: 4.9,
        vote_count: 23000
    },
    {
        adult: false,
        backdrop_path: "/path14.jpg",
        genre_ids: [12, 878],
        id: 114,
        original_language: "en",
        original_title: "Avatar",
        overview: "On the lush alien world of Pandora...",
        popularity: 990.1,
        poster_path: "https://www.slashfilm.com/img/gallery/the-10-best-moments-in-avatar-the-way-of-water/l-intro-1671230908.jpg",
        release_date: "2009-12-18",
        title: "Avatar",
        video: false,
        vote_average: 8.2,
        vote_count: 24000
    },
    {
        adult: false,
        backdrop_path: "/path16.jpg",
        genre_ids: [35, 18],
        id: 116,
        original_language: "en",
        original_title: "The Wolf of Wall Street",
        overview: "Based on the true story of Jordan Belfort...",
        popularity: 720.3,
        poster_path: "https://static1.srcdn.com/wordpress/wp-content/uploads/2023/09/howoldwas_margotrobbie_inwolfofwallstreet.jpg",
        release_date: "2013-12-25",
        title: "The Wolf of Wall Street",
        video: false,
        vote_average: 4.3,
        vote_count: 17000
    },

]